### ISSUE TITLE
How to paginate older messages? Would prefer to not have infinite scroll

### ISSUE THREAD

**Issue by operatorjen** [mozilla/chatspaces#7]

**Comment by operatorjen** [comment]
GIF performance on mobile is pretty chuggy.. I would like to reduce the load of this as much as possible. Setting a default load of 5 messages for now.

**Comment by fwenzel** [comment]
Should the gifs (all but the last one) be click-to-play? But then we need to generate a still frame as the messages come in.

**Comment by sole** [comment]
I think we can just "copy" the gif to canvas and it generates always the same still image, so we don't even need to store the static frame apart.

**Comment by operatorjen** [comment]
I think part of the charm in this kind of chat is that the gif plays right away. Unlike Tumblr, the gifs are part of messages, not blog posts.. so the click to play might interrupt the flow of fast response, fast post. We should talk to Maureen about it and see what she thinks before implementing anything.

**Comment by mhanratty** [comment]
I agree that the gif should play right away--it will make the app much more fun. Two proposals...
1. Old school pagination. X number of messages per screen. User keeps moving back in time by clicking link to view previous group of messages.
2. Load more. Load older messages on same screen but show still images for gifs and have them click to play.

More ideas?

**Comment by operatorjen** [comment]
I think old school pagination is good for now actually - at least we'll know it works and we can control the load of gifs in memory and not kill the battery too badly :)

**Comment by sole** [comment]
Heelloo! I'm back from my away-ness.

I actually encountered something similar when doing rtcamera and kind of solved it _temporarily_ setting gifs outside the viewport to not to show. But I reckon a better solution for the user would be to have "infinite scroll" although it technically wouldn't be that but a "window" showing part of the list. This is something we must implement anyway if you want to do things properly for mobile, so I can take a look into it.

For now we should start with old school pagination, and in the future once I write this magic piece of technology we can replace so that scrolling up or down will load/hide the messages automatically.

**Comment by operatorjen** [comment]
@sole yep that makes sense! old school pagination for now to get it working and then we can go do a phase 2 post mwc

**Comment by sole** [comment]
sounds good to me, it is a component desperately needed for Brick (as it is two apps that require it already, haha)

**Comment by mhanratty** [comment]
I like the Twitter bootstrap components for pagination: http://getbootstrap.com/2.3.2/components.html#pagination
• Mobile & Tablet: Show "Older" and "Newer"
• Desktop: Show "<< 1 2 3 4 5 >>"

We could also do some fun copy here. Instead of "Older" "Newer" it could be "Fresh/Vintage" or "Wired/Tired". The world is our oyster. 

![2013-11-20 16 45 13](https://f.cloud.github.com/assets/4432402/1587991/8a249ec6-5246-11e3-9b79-525d509003ba.jpg)

**Comment by operatorjen** [comment]
I can't believe I'm saying this but after hacking on the pagination behaviour, I've realized the prev/next model is incorrect for this format. What we can do a la meatspace is freeze the content above if it is out of the view and load more if you reach the bottom. (I still can't believe I am okay with infinite scroll, kill me now)

**Comment by sole** [comment]
It's OK to be wrong-it's a sign of wisdom :P
